
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
[Serializable]
    public partial class UserInfo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserInfo()
    {

        this.R_UserInfo_ActionInfo = new HashSet<R_UserInfo_ActionInfo>();

        this.Department = new HashSet<Department>();

        this.RoleInfo = new HashSet<RoleInfo>();

    }


    public int ID { get; set; }

    public string UName { get; set; }

    public string UPwd { get; set; }

    public System.DateTime SubTime { get; set; }

    public short DelFlag { get; set; }

    public System.DateTime ModifiedOn { get; set; }

    public string Remark { get; set; }

    public string Sort { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Department> Department { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RoleInfo> RoleInfo { get; set; }

}

}
